-- Xavier Planner OS Ultimate modules.
-- Adds the full life operating system layer: workspaces, notes, habits, journal,
-- finance, contacts, calendar events, templates, AI memory, vault, trackers and activity.
create extension if not exists pgcrypto;

alter table public.planner_tasks drop constraint if exists planner_tasks_level_check;
alter table public.planner_tasks add constraint planner_tasks_level_check check (level in ('life','decade','yearly','quarterly','monthly','weekly','daily','hourly','task','subtask'));

create table if not exists public.xp_workspaces (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, name text not null default 'Xavier Planner OS', theme text not null default 'midnight', settings jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.xp_life_areas (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, name text not null, color text not null default '#8b7cff', icon text not null default 'circle', description text not null default '', score integer not null default 5 check (score between 0 and 10), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.xp_notes (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, task_id uuid references public.planner_tasks(id) on delete set null, title text not null, body text not null default '', kind text not null default 'note', tags text[] not null default '{}', metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.xp_journal_entries (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, entry_date date not null default current_date, mood integer not null default 5 check (mood between 1 and 10), energy integer not null default 5 check (energy between 1 and 10), gratitude text not null default '', wins text not null default '', lessons text not null default '', body text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(user_id, entry_date));
create table if not exists public.xp_habits (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, name text not null, cadence text not null default 'daily', target integer not null default 1, unit text not null default 'times', color text not null default '#68d9ba', active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.xp_habit_logs (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, habit_id uuid not null references public.xp_habits(id) on delete cascade, log_date date not null default current_date, value integer not null default 1, notes text not null default '', created_at timestamptz not null default now(), unique(user_id, habit_id, log_date));
create table if not exists public.xp_finance_items (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, name text not null, amount numeric(14,2) not null default 0, currency text not null default 'AUD', category text not null default 'general', kind text not null default 'expense', due_date date, recurring boolean not null default false, notes text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.xp_contacts (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, name text not null, role text not null default '', email text not null default '', phone text not null default '', birthday date, notes text not null default '', tags text[] not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.xp_calendar_events (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, task_id uuid references public.planner_tasks(id) on delete set null, title text not null, starts_at timestamptz not null, ends_at timestamptz, location text not null default '', notes text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.xp_templates (id uuid primary key default gen_random_uuid(), user_id uuid default auth.uid() references auth.users(id) on delete cascade, name text not null, category text not null default 'planner', description text not null default '', payload jsonb not null default '{}'::jsonb, public_template boolean not null default false, created_at timestamptz not null default now());
create table if not exists public.xp_ai_memory (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, memory_type text not null default 'planning_preference', content text not null, weight integer not null default 5, source text not null default 'user', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.xp_vault_items (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, title text not null, category text not null default 'document', storage_path text, expiry_date date, notes text not null default '', metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.xp_trackers (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, module text not null, title text not null, status text not null default 'active', target_date date, data jsonb not null default '{}'::jsonb, notes text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.xp_activity_log (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, action text not null, entity_type text not null, entity_id uuid, details jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());

alter table public.xp_workspaces enable row level security; alter table public.xp_life_areas enable row level security; alter table public.xp_notes enable row level security; alter table public.xp_journal_entries enable row level security; alter table public.xp_habits enable row level security; alter table public.xp_habit_logs enable row level security; alter table public.xp_finance_items enable row level security; alter table public.xp_contacts enable row level security; alter table public.xp_calendar_events enable row level security; alter table public.xp_templates enable row level security; alter table public.xp_ai_memory enable row level security; alter table public.xp_vault_items enable row level security; alter table public.xp_trackers enable row level security; alter table public.xp_activity_log enable row level security;

do $$ declare t text; begin foreach t in array array['xp_workspaces','xp_life_areas','xp_notes','xp_journal_entries','xp_habits','xp_habit_logs','xp_finance_items','xp_contacts','xp_calendar_events','xp_ai_memory','xp_vault_items','xp_trackers','xp_activity_log'] loop execute format('drop policy if exists "%I_owner_all" on public.%I', t, t); execute format('create policy "%I_owner_all" on public.%I for all to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()))', t, t); execute format('grant select,insert,update,delete on public.%I to authenticated', t); execute format('revoke all on public.%I from anon', t); end loop; end $$;

drop policy if exists "xp_templates_owner_or_public" on public.xp_templates; create policy "xp_templates_owner_or_public" on public.xp_templates for select to authenticated using (public_template or user_id = (select auth.uid()));
drop policy if exists "xp_templates_owner_write" on public.xp_templates; create policy "xp_templates_owner_write" on public.xp_templates for all to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
grant select,insert,update,delete on public.xp_templates to authenticated; revoke all on public.xp_templates from anon;

insert into storage.buckets (id,name,public,file_size_limit) values ('planner-vault','planner-vault',false,52428800) on conflict (id) do update set public=false, file_size_limit=52428800;
drop policy if exists "planner_vault_read" on storage.objects; create policy "planner_vault_read" on storage.objects for select to authenticated using (bucket_id='planner-vault' and (storage.foldername(name))[1] = (select auth.uid())::text);
drop policy if exists "planner_vault_insert" on storage.objects; create policy "planner_vault_insert" on storage.objects for insert to authenticated with check (bucket_id='planner-vault' and (storage.foldername(name))[1] = (select auth.uid())::text);
drop policy if exists "planner_vault_update" on storage.objects; create policy "planner_vault_update" on storage.objects for update to authenticated using (bucket_id='planner-vault' and (storage.foldername(name))[1] = (select auth.uid())::text) with check (bucket_id='planner-vault' and (storage.foldername(name))[1] = (select auth.uid())::text);
drop policy if exists "planner_vault_delete" on storage.objects; create policy "planner_vault_delete" on storage.objects for delete to authenticated using (bucket_id='planner-vault' and (storage.foldername(name))[1] = (select auth.uid())::text);

-- Cover foreign keys for production performance.
create index if not exists xp_activity_log_user_id_idx on public.xp_activity_log(user_id);
create index if not exists xp_ai_memory_user_id_idx on public.xp_ai_memory(user_id);
create index if not exists xp_calendar_events_task_id_idx on public.xp_calendar_events(task_id);
create index if not exists xp_contacts_user_id_idx on public.xp_contacts(user_id);
create index if not exists xp_habit_logs_habit_id_idx on public.xp_habit_logs(habit_id);
create index if not exists xp_habits_user_id_idx on public.xp_habits(user_id);
create index if not exists xp_life_areas_user_id_idx on public.xp_life_areas(user_id);
create index if not exists xp_notes_task_id_idx on public.xp_notes(task_id);
create index if not exists xp_templates_user_id_idx on public.xp_templates(user_id);
create index if not exists xp_vault_items_user_id_idx on public.xp_vault_items(user_id);
create index if not exists xp_workspaces_user_id_idx on public.xp_workspaces(user_id);

-- Avoid duplicate SELECT permissive policies on templates.
drop policy if exists "xp_templates_owner_write" on public.xp_templates;
drop policy if exists "xp_templates_owner_insert" on public.xp_templates;
drop policy if exists "xp_templates_owner_update" on public.xp_templates;
drop policy if exists "xp_templates_owner_delete" on public.xp_templates;
create policy "xp_templates_owner_insert" on public.xp_templates for insert to authenticated with check (user_id = (select auth.uid()));
create policy "xp_templates_owner_update" on public.xp_templates for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy "xp_templates_owner_delete" on public.xp_templates for delete to authenticated using (user_id = (select auth.uid()));
